// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jddchtoajlkyskpyfzxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZGNodG9hamxreXNrcHlmenh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQ1ODcsImV4cCI6MjA2NTU5MDU4N30.mrv8nT4MiH1gs4FdjYV-6P4n7YWbId0I1nWAzDWSpjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);